### ISSUE TITLE
Screen Selection and Global Take

### ISSUE THREAD

**Issue by loechri** [bitfocus/companion-module-analogway-livecore#2]
On my system Screen Selection with Global Take is not working. I use two linked Ascender 3204, a two Output Widescreen, five Singlescreen Destinations and a Confidence Output.
All other Commands are working fine!
Can't figure out where the Problem is...
I'm doing the Selection and then the Global Take on one Button.

**Comment by dnmeid** [comment]
Quite old issue, usually issues with Global Take used to be user errors.
I'll close this issue due to age soon unless @loechri doesn't say he still has the problem.
