### ISSUE TITLE
Analog Way NeXtage 08 - 4K Variant

### ISSUE THREAD

**Issue by WillTaylor-11** [bitfocus/companion-module-analogway-livecore#6]
Can you please add support to the Analog Way livecore Module for the NeXtage 08 - 4k Variant.

The Variant value is 117.

Please let me know if you need any additional information.

Thank you.

**Comment by Bobbyama** [comment]
Newsss nextage 4k?

**Comment by dnmeid** [comment]
It was planned to use the variant for generating the correct number of inputs and outputs for offline editing but this never made it to the code.
The way it currently works is that you always have the maximum number of inputs and screens for the whole Livecore series available.
This includes Nextage 08 4k.
As the Series is quite old and end of life, I won't put much efforts in updating. That means it is a won't fix.
