### ISSUE TITLE
Ascender 32 4k triggers

### ISSUE THREAD

**Issue by ferromanu** [bitfocus/companion-module-analogway-livecore#7]
Ascender 32 4k triggers only do take no matter what master memory is set to load...
Only when i restart the companion its starts to work properly again

**Comment by dnmeid** [comment]
Sorry, can you please explain your problem in more detail. I can't follow you.

**Comment by ferromanu** [comment]
Not relevant anymore, fixed the issue with new module that gave the option of choosing which outputs to take
